# Basic
name:               "Rohan Pai"
description:        "Rohan Pai"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
url:                "//rohanpai.com"
author:             "Rohanpai"
twitter:
  username:         "rohanpai25"
#facebook:
#  app_id:           1234
#    publisher:      1234

# URL
#baseurl:            "https://rohanpai.github.io/website"
baseurl: ""
#baseurl:            "http://qasaryounis.com" #For Root Domain
permalink:          /essays/:title/

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "Writings"
    href:           "writing"
  - name:           "Bookshelf"
    href:           "readings"
  - name:           "About Me"
    href:           "about"



# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-seo-tag
